#!/command/with-contenv /bin/bash
#shellcheck shell=bash

NOCOLOR='\033[0m'
YELLOW='\033[1;33m'
LIGHTRED='\033[1;31m'
LIGHTBLUE='\033[1;34m'

# Check to make sure the correct command line arguments have been set
EXITCODE=0
if [ -z "${FAM_INSTALLPASSWORD}" ]; then
  echo -e "${YELLOW}WARNING: FAM_INSTALLPASSWORD environment variable not set, using random password${NOCOLOR}"
  #EXITCODE=1
fi

# Make sure database hostname/password have been set OK
if [ -z "${MYSQLHOSTNAME}" ]; then
  echo -e "${LIGHTBLUE}INFO: MYSQLHOSTNAME not set, using local database${NOCOLOR}"
  echo -e "${LIGHTRED}ERROR: local data base is not supported. Please set up an external mariadb instance for use.${NOCOLOR}"
  EXITCODE=1
else
  if [ -z "${MYSQLPASSWORD}" ]; then
    echo -e "${LIGHTRED}ERROR: MYSQLHOSTNAME set, however MYSQLPASSWORD not set${NOCOLOR}"
    EXITCODE=1
  fi
fi

# If any sanity checks if failed, exit
if [ "$EXITCODE" -ne 0 ]; then
  exit 1
fi

# Set up timezone
ln -snf "/usr/share/zoneinfo/$TZ" /etc/localtime && echo "$TZ" > /etc/timezone
