#!/command/with-contenv bash
# shellcheck shell=bash

source /scripts/common

s6wrap=(s6wrap --quiet --prepend="$(basename "$0")" --timestamps --args)
if chk_enabled $QUIET_FAM; then
    "${s6wrap[@]}" s6-setuidgid "$WEBUSER" php /var/www/flightairmap/htdocs/scripts/daemon-spotter.php 2>&1 | \
            stdbuf -oL awk '! /\\o\//' | \
            stdbuf -oL awk '! /DATA : /' | \
            stdbuf -oL awk '! /New flight.../' | \
            stdbuf -oL awk '! /New aircraft hex/' | \
            stdbuf -oL awk '! /in archive DB/' | \
            stdbuf -oL awk '! /already in DB/' | \
            stdbuf -oL awk '! /Getting schedule info/' | \
            stdbuf -oL awk '! /old values and update latest data/' | \
            stdbuf -oL awk '! /Check if aircraft is already in DB/' | \
            stdbuf -oL awk '! /get arrival\/departure airport/' | \
            stdbuf -oL awk '! /Deleting Live Spotter/' | \
            stdbuf -oL awk '! /Calculated Speed/' | \
            stdbuf -oL awk '{print $0}'
else
    "${s6wrap[@]}" s6-setuidgid "$WEBUSER" php /var/www/flightairmap/htdocs/scripts/daemon-spotter.php
fi
