#!/command/with-contenv bash
# shellcheck shell=bash

# shellcheck disable=SC1091,SC2086,SC2016
source /scripts/common

s6wrap=(s6wrap --quiet --prepend="$(basename "$0")" --timestamps --args)

if [ -z "${BASESTATIONHOST}" ]; then
  "${s6wrap[@]}" sleep 3600
else
  # shellcheck disable=SC2153
  "${s6wrap[@]}" socat -d -d TCP-LISTEN:30003,fork TCP:"${BASESTATIONHOST}":"${BASESTATIONPORT}"
fi
