#!/command/with-contenv sh
# shellcheck shell=sh

s6wrap=(s6wrap --quiet --prepend="$(basename "$0")" --timestamps --args)
"${s6wrap[@]}" sleep 1h
"${s6wrap[@]}" s6-setuidgid "$WEBUSER" php /var/www/flightairmap/htdocs/scripts/update_db.php 2>&1 | awk '{print "[update_db] " $0}'
