#!/command/with-contenv bash
# shellcheck shell=bash

# shellcheck disable=SC1091,SC2086,SC2016
source /scripts/common

s6wrap=(s6wrap --quiet --prepend="$(basename "$0")" --timestamps --args)
"${s6wrap[@]}" sleep 1h
"${s6wrap[@]}" s6-setuidgid "$WEBUSER" php /var/www/flightairmap/htdocs/scripts/update_db.php
